version: "3"
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./storage/mysql/data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/my.cnf
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--init-connect="SET NAMES UTF8"', '--innodb-flush-log-at-trx-commit=0']
    ports:
      - "3306:3306"
networks:
  study: